/**
 * PHARMAVITA / CLINICALRX - DỊCH VỤ CƠ SỞ DỮ LIỆU ĐÁM MÂY (SUPABASE CLOUD SERVICE)
 * Đồng bộ thời gian thực giữa tất cả các máy tính / điện thoại
 */

import { CONFIG, getSupabaseCredentials, saveSupabaseCredentials } from "../config.js";

const CUSTOM_DRUGS_STORAGE_KEY = "clinicalrx_custom_drugs_store_v4";

let supabaseClient = null;

export const SUPABASE_SCHEMA_SQL = `-- PHARMAVITA / CLINICALRX - SUPABASE DATABASE SCHEMA V3
-- Chạy trong Supabase SQL Editor để khởi tạo toàn bộ CSDL

-- 1. BẢNG HỒ SƠ NGƯỜI DÙNG (PROFILES)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text not null,
  role text not null default 'Bác sĩ' check (role in ('Bác sĩ', 'Dược sĩ lâm sàng', 'Điều dưỡng', 'Admin')),
  department text,
  license_number text,
  phone text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2. BẢNG YÊU CẦU TƯ VẤN & HỎI ĐÁP THÔNG TIN THUỐC (CONSULTATIONS)
create table if not exists public.consultations (
  id bigint generated by default as identity primary key,
  doctor_id uuid references public.profiles(id) on delete set null,
  pharmacist_id uuid references public.profiles(id),
  title text not null,
  category text not null default 'Chỉnh liều',
  urgency text not null default 'Thường quy',
  patient_age integer,
  patient_gender text,
  patient_weight numeric(5,2),
  patient_creatinine numeric(5,2),
  clinical_diagnosis text,
  current_medications text,
  inquiry_content text not null,
  pharmacist_answer text,
  references_text text,
  status text not null default 'pending',
  doctor_name text,
  pharmacist_name text,
  created_at timestamptz not null default now(),
  answered_at timestamptz,
  updated_at timestamptz not null default now()
);

-- 3. BẢNG BÁO CÁO PHẢN ỨNG CÓ HẠI CỦA THUỐC (ADR REPORTS)
create table if not exists public.adr_reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid references public.profiles(id) on delete set null,
  patient_code text not null,
  patient_age integer,
  patient_gender text,
  patient_weight numeric(5,2),
  suspected_drug text not null,
  dosage_and_route text,
  indication text,
  reaction_description text not null,
  reaction_onset timestamptz,
  severity text not null default 'Nghiêm trọng',
  outcome text,
  dechallenge text,
  rechallenge text,
  causality_assessment text,
  reporter_name text,
  reporter_dept text,
  created_at timestamptz not null default now()
);

-- 4. BẢNG DƯỢC THƯ NỘI VIỆN & THUỐC TÙY BIẾN ĐỒNG BỘ ĐÁM MÂY (CUSTOM DRUGS)
create table if not exists public.custom_drugs (
  id text primary key,
  data jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- KÍCH HOẠT ROW LEVEL SECURITY (RLS)
alter table public.profiles enable row level security;
alter table public.consultations enable row level security;
alter table public.adr_reports enable row level security;
alter table public.custom_drugs enable row level security;

-- CHÍNH SÁCH BẢO MẬT & TRUY CẬP (POLICIES)
drop policy if exists "Public read custom_drugs" on public.custom_drugs;
create policy "Public read custom_drugs" on public.custom_drugs for select using (true);

drop policy if exists "Allow insert custom_drugs" on public.custom_drugs;
create policy "Allow insert custom_drugs" on public.custom_drugs for insert with check (true);

drop policy if exists "Allow update custom_drugs" on public.custom_drugs;
create policy "Allow update custom_drugs" on public.custom_drugs for update using (true);

drop policy if exists "Allow delete custom_drugs" on public.custom_drugs;
create policy "Allow delete custom_drugs" on public.custom_drugs for delete using (true);

drop policy if exists "Public read consultations" on public.consultations;
create policy "Public read consultations" on public.consultations for select using (true);

drop policy if exists "Public insert consultations" on public.consultations;
create policy "Public insert consultations" on public.consultations for insert with check (true);

drop policy if exists "Public update consultations" on public.consultations;
create policy "Public update consultations" on public.consultations for update using (true);

drop policy if exists "Public read adr" on public.adr_reports;
create policy "Public read adr" on public.adr_reports for select using (true);

drop policy if exists "Public insert adr" on public.adr_reports;
create policy "Public insert adr" on public.adr_reports for insert with check (true);

-- CẤP QUYỀN TRUY CẬP CHO ANON VÀ AUTHENTICATED
grant all on public.custom_drugs to anon, authenticated, service_role;
grant all on public.consultations to anon, authenticated, service_role;
grant all on public.adr_reports to anon, authenticated, service_role;
grant all on public.profiles to anon, authenticated, service_role;

-- 5. KHO LƯU TRỮ FILE PDF THUỐC ĐỒNG BỘ ĐÁM MÂY (SUPABASE STORAGE: drug-pdfs)
insert into storage.buckets (id, name, public) 
values ('drug-pdfs', 'drug-pdfs', true) 
on conflict (id) do update set public = true;

drop policy if exists "Public read drug-pdfs" on storage.objects;
create policy "Public read drug-pdfs" on storage.objects for select using (bucket_id = 'drug-pdfs');

drop policy if exists "Public insert drug-pdfs" on storage.objects;
create policy "Public insert drug-pdfs" on storage.objects for insert with check (bucket_id = 'drug-pdfs');

drop policy if exists "Public update drug-pdfs" on storage.objects;
create policy "Public update drug-pdfs" on storage.objects for update using (bucket_id = 'drug-pdfs');

drop policy if exists "Public delete drug-pdfs" on storage.objects;
create policy "Public delete drug-pdfs" on storage.objects for delete using (bucket_id = 'drug-pdfs');
`;

export function getSupabaseClient() {
  if (supabaseClient) return supabaseClient;
  const { url, key } = getSupabaseCredentials();
  if (url && key && window.supabase) {
    try {
      supabaseClient = window.supabase.createClient(url, key);
    } catch (e) {
      console.warn("Lỗi khởi tạo Supabase Client:", e);
    }
  }
  return supabaseClient;
}

export async function testSupabaseConnection(customUrl = null, customKey = null) {
  const url = customUrl || getSupabaseCredentials().url;
  const key = customKey || getSupabaseCredentials().key;

  if (!url || !key) {
    return { ok: false, message: "Chưa cấu hình Supabase URL hoặc Key." };
  }
  if (!window.supabase) {
    return { ok: false, message: "Thư viện Supabase JS chưa được tải." };
  }

  try {
    const testClient = window.supabase.createClient(url, key);
    const { data, error } = await testClient.from("custom_drugs").select("id").limit(1);
    if (error) {
      if (error.code === "42P01") {
        return {
          ok: false,
          needSql: true,
          message: "Kết nối thành công tới Supabase, nhưng bảng 'custom_drugs' chưa tồn tại. Vui lòng chạy mã SQL khởi tạo."
        };
      }
      if (error.code === "42501") {
        return {
          ok: false,
          needSql: true,
          message: "Quyền truy cập bảng bị hạn chế (RLS). Vui lòng chạy mã SQL khởi tạo để mở quyền."
        };
      }
      return { ok: false, message: `Lỗi từ Supabase: ${error.message}` };
    }
    let storageStatus = "";
    try {
      const { data: buckets } = await testClient.storage.listBuckets();
      if (buckets && buckets.some(b => b.name === "drug-pdfs" || b.id === "drug-pdfs")) {
        storageStatus = " | Kho lưu trữ PDF Cloud (Storage: drug-pdfs) đã SẴN SÀNG!";
      } else {
        storageStatus = " | Lưu ý: Cần bấm nút sao chép mã SQL bên dưới chạy trong SQL Editor để kích hoạt Kho PDF liên máy (drug-pdfs).";
      }
    } catch (stErr) {}

    return {
      ok: true,
      message: "Kết nối thành công! Đã kết nối thông suốt với Cơ sở dữ liệu Supabase Cloud." + storageStatus
    };
  } catch (err) {
    return { ok: false, message: `Lỗi kết nối mạng: ${err.message}` };
  }
}

export async function syncCustomDrugsFromCloud() {
  const client = getSupabaseClient();
  if (!client) return false;

  try {
    const { data, error } = await client.from("custom_drugs").select("*");
    if (error) {
      console.warn("Lỗi tải custom_drugs từ Supabase:", error);
      return false;
    }

    if (Array.isArray(data) && data.length > 0) {
      const raw = localStorage.getItem(CUSTOM_DRUGS_STORAGE_KEY);
      let store;
      try {
        if (raw && (/[\x00-\x08\x0B\x0C\x0E-\x1F]/.test(raw) || raw.includes("\\u0010") || raw.includes("\\u0001"))) {
          console.log("Phát hiện bộ nhớ cache cũ bị lỗi font ký tự lạ, tiến hành dọn sạch và nạp dữ liệu chuẩn từ Cloud...");
          store = { deletedIds: [], modified: {}, addedDrugs: [] };
        } else {
          store = raw ? JSON.parse(raw) : { deletedIds: [], modified: {}, addedDrugs: [] };
        }
      } catch (pe) {
        store = { deletedIds: [], modified: {}, addedDrugs: [] };
      }
      if (!store.addedDrugs) store.addedDrugs = [];

      // Dọn dẹp cache nếu có chứa video metadata
      if (Array.isArray(store.addedDrugs)) {
        store.addedDrugs = store.addedDrugs.filter(ad => ad && ad.id && !ad.id.startsWith("video_") && (ad.name || ad.inn));
      }
      if (store.modified && typeof store.modified === "object") {
        Object.keys(store.modified).forEach(k => {
          if (k.startsWith("video_") || (!store.modified[k]?.name && !store.modified[k]?.inn)) {
            delete store.modified[k];
          }
        });
      }

      data.forEach(row => {
        const drug = row.data || row;
        if (!drug || !drug.id || drug.id.startsWith("video_") || (!drug.name && !drug.inn)) return;
        
        // Luôn lưu vào modified để áp dụng cho cả thuốc trong cơ sở dữ liệu gốc (như Tranexamic, Vitamin 3B)
        store.modified[drug.id] = drug;

        const idx = store.addedDrugs.findIndex(d => d.id === drug.id);
        if (idx >= 0) {
          store.addedDrugs[idx] = drug;
        } else {
          store.addedDrugs.push(drug);
        }
      });

      localStorage.setItem(CUSTOM_DRUGS_STORAGE_KEY, JSON.stringify(store));
      console.log(`Đã đồng bộ thuốc từ Supabase Cloud!`);
      if (window.renderDrugList) window.renderDrugList();
      return true;
    }
  } catch (e) {
    console.warn("Lỗi syncCustomDrugsFromCloud:", e);
  }
  return false;
}

export async function saveDrugToCloud(drugData) {
  const client = getSupabaseClient();
  if (!client || !drugData || !drugData.id) return false;

  try {
    const { error } = await client.from("custom_drugs").upsert({
      id: drugData.id,
      data: drugData,
      updated_at: new Date().toISOString()
    });
    if (error) {
      console.warn("Lỗi lưu thuốc lên Supabase Cloud:", error);
      return false;
    }
    console.log("Đã lưu thuốc lên Supabase Cloud:", drugData.name);
    return true;
  } catch (e) {
    console.warn("Lỗi saveDrugToCloud:", e);
    return false;
  }
}

export async function deleteDrugFromCloud(drugId) {
  const client = getSupabaseClient();
  if (!client || !drugId) return false;

  try {
    const { error } = await client.from("custom_drugs").delete().eq("id", drugId);
    if (error) {
      console.warn("Lỗi xóa thuốc trên Supabase Cloud:", error);
      return false;
    }
    console.log("Đã xóa thuốc trên Supabase Cloud:", drugId);
    return true;
  } catch (e) {
    console.warn("Lỗi deleteDrugFromCloud:", e);
    return false;
  }
}


export async function dataUrlToBlob(dataUrl) {
  try {
    const res = await fetch(dataUrl);
    return await res.blob();
  } catch (err) {
    try {
      const parts = dataUrl.split(";base64,");
      const contentType = parts[0].split(":")[1] || "application/pdf";
      const raw = atob(parts[1]);
      const rawLength = raw.length;
      const uInt8Array = new Uint8Array(rawLength);
      for (let i = 0; i < rawLength; ++i) {
        uInt8Array[i] = raw.charCodeAt(i);
      }
      return new Blob([uInt8Array], { type: contentType });
    } catch (e2) {
      console.error("Lỗi chuyển đổi DataURL sang Blob:", e2);
      return null;
    }
  }
}

export function sanitizeFileName(name) {
  return (name || "document.pdf")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/đ/g, "d").replace(/Đ/g, "D")
    .replace(/[^a-zA-Z0-9._-]/g, "_");
}

export async function uploadPdfToSupabaseStorage(fileOrDataUrl, drugId, fileName) {
  const client = getSupabaseClient();
  if (!client) {
    console.warn("Chưa kết nối Supabase client để upload PDF.");
    return null;
  }

  try {
    let blob = null;
    if (typeof fileOrDataUrl === "string" && fileOrDataUrl.startsWith("data:")) {
      blob = await dataUrlToBlob(fileOrDataUrl);
    } else if (fileOrDataUrl instanceof Blob || fileOrDataUrl instanceof File) {
      blob = fileOrDataUrl;
    }

    if (!blob) {
      console.warn("Dữ liệu PDF không hợp lệ để tải lên Supabase.");
      return null;
    }

    const cleanName = sanitizeFileName(fileName || "document.pdf");
    const safeDrugId = sanitizeFileName(drugId || "general");
    const storagePath = `${safeDrugId}/${cleanName}`;

    const { data, error } = await client.storage
      .from("drug-pdfs")
      .upload(storagePath, blob, {
        contentType: "application/pdf",
        upsert: true
      });

    if (error) {
      console.warn("Lỗi tải PDF lên Supabase Storage:", error.message);
      return null;
    }

    const { data: publicData } = client.storage
      .from("drug-pdfs")
      .getPublicUrl(storagePath);

    const publicUrl = publicData?.publicUrl || null;
    console.log("Đã tải PDF lên Supabase Storage thành công:", publicUrl);
    return publicUrl;
  } catch (err) {
    console.warn("Lỗi uploadPdfToSupabaseStorage:", err);
    return null;
  }
}

export async function autoHealMissingCloudPdfs() {
  const client = getSupabaseClient();
  if (!client || typeof window === "undefined") return;

  try {
    const raw = localStorage.getItem(CUSTOM_DRUGS_STORAGE_KEY);
    if (!raw) return;
    const store = JSON.parse(raw);
    let changed = false;

    const allDrugs = [...(store.addedDrugs || []), ...Object.values(store.modified || {})];
    for (const drug of allDrugs) {
      if (!drug || !Array.isArray(drug.attachments)) continue;
      for (const att of drug.attachments) {
        if (!att.fileUrl) {
          let sourceData = att.dataUrl;
          if (!sourceData && window.getPdfAttachmentById) {
            const localAtt = await window.getPdfAttachmentById(att.id);
            if (localAtt && localAtt.dataUrl) {
              sourceData = localAtt.dataUrl;
            }
          }
          if (sourceData) {
            console.log("Tự động vá PDF lên Supabase Storage:", att.fileName);
            const uploadedUrl = await uploadPdfToSupabaseStorage(sourceData, drug.id, att.fileName);
            if (uploadedUrl) {
              att.fileUrl = uploadedUrl;
              changed = true;
              await saveDrugToCloud(drug);
              console.log("Đã tự động cập nhật URL Cloud cho:", att.fileName);
            }
          }
        }
      }
    }
    if (changed) {
      localStorage.setItem(CUSTOM_DRUGS_STORAGE_KEY, JSON.stringify(store));
      if (window.renderDrugList) window.renderDrugList();
    }
  } catch (e) {
    console.warn("autoHealMissingCloudPdfs warning:", e);
  }
}

export function copySupabaseSchemaSql() {
  if (navigator.clipboard) {
    navigator.clipboard.writeText(SUPABASE_SCHEMA_SQL).then(() => {
      alert("Đã sao chép toàn bộ mã SQL khởi tạo CSDL vào bộ nhớ tạm!\n\nBây giờ bạn hãy mở Supabase Dashboard -> SQL Editor -> Dán (Ctrl+V) và bấm RUN.");
    }).catch(() => {
      prompt("Hãy sao chép đoạn mã SQL dưới đây:", SUPABASE_SCHEMA_SQL);
    });
  } else {
    prompt("Hãy sao chép đoạn mã SQL dưới đây:", SUPABASE_SCHEMA_SQL);
  }
}

export function openSupabaseModal() {
  let modalContainer = document.getElementById("supabaseAuthModal");
  if (!modalContainer) {
    modalContainer = document.createElement("div");
    modalContainer.id = "supabaseAuthModal";
    document.body.appendChild(modalContainer);
  }

  const { url, key } = getSupabaseCredentials();

  modalContainer.innerHTML = `
    <div class="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-sm flex items-center justify-center p-3 sm:p-4 overflow-y-auto">
      <div class="bg-white w-full max-w-lg rounded-2xl shadow-2xl border border-slate-100 overflow-hidden flex flex-col animate-in fade-in duration-200">
        
        <!-- Header -->
        <div class="px-5 py-4 bg-gradient-to-r from-teal-900 via-teal-800 to-slate-900 text-white flex items-center justify-between">
          <div class="flex items-center gap-2.5">
            <div class="w-8 h-8 rounded-xl bg-teal-500/20 border border-teal-400/30 flex items-center justify-center text-teal-300">
              <i data-lucide="database" class="w-4 h-4"></i>
            </div>
            <div>
              <h3 class="text-sm sm:text-base font-bold">Cơ Sở Dữ Liệu Đám Mây (Supabase)</h3>
              <p class="text-[11px] text-teal-200/80">Tự động đồng bộ thuốc & dữ liệu cho tất cả các máy tính</p>
            </div>
          </div>
          <button onclick="window.closeSupabaseAuthModal()" class="text-white/70 hover:text-white p-1 rounded-lg hover:bg-white/10 transition-colors cursor-pointer">
            <i data-lucide="x" class="w-5 h-5"></i>
          </button>
        </div>

        <div class="p-5 sm:p-6 space-y-4 text-xs text-slate-700 max-h-[75vh] overflow-y-auto">
          
          <!-- Banner Trạng thái -->
          <div id="supabaseStatusBanner" class="p-3.5 rounded-xl border border-teal-200 bg-teal-50/70 flex items-start gap-3">
            <div class="w-2.5 h-2.5 rounded-full bg-teal-500 mt-1 shrink-0 animate-pulse"></div>
            <div class="flex-1">
              <div class="font-bold text-teal-950 text-xs">Cấu hình kết nối hiện tại</div>
              <p class="text-[11px] text-teal-800 mt-0.5" id="supabaseStatusText">
                Đang cấu hình dự án Supabase nội viện BVĐK tỉnh Hưng Yên. Bấm "Kiểm tra kết nối" bên dưới để xác nhận.
              </p>
            </div>
          </div>

          <!-- Nhập URL & Key -->
          <div class="space-y-3 bg-slate-50 p-4 rounded-xl border border-slate-200">
            <div>
              <label class="font-bold text-slate-800 block mb-1">Supabase Project URL:</label>
              <input id="cfgSupabaseUrl" type="text" value="\${url}" placeholder="https://xyzcompany.supabase.co" 
                class="w-full p-2.5 border border-slate-300 rounded-xl focus:ring-2 focus:ring-teal-500 font-mono text-xs bg-white">
            </div>

            <div>
              <label class="font-bold text-slate-800 block mb-1">Supabase Anon / Publishable Key:</label>
              <input id="cfgSupabaseKey" type="text" value="\${key}" placeholder="sb_publishable_... hoặc eyJhbGciOi..." 
                class="w-full p-2.5 border border-slate-300 rounded-xl focus:ring-2 focus:ring-teal-500 font-mono text-xs bg-white">
            </div>

            <div class="flex items-center gap-2 pt-1 flex-wrap">
              <button onclick="window.handleTestSupabaseConnection()" 
                id="btnTestConnection"
                class="px-3.5 py-2 bg-teal-700 hover:bg-teal-800 text-white rounded-xl font-bold text-xs flex items-center gap-1.5 transition-colors cursor-pointer shadow-xs">
                <i data-lucide="activity" class="w-3.5 h-3.5"></i>
                <span>Kiểm tra kết nối</span>
              </button>
              <button onclick="window.saveSupabaseConfig()" 
                class="px-3.5 py-2 bg-slate-800 hover:bg-slate-900 text-white rounded-xl font-bold text-xs flex items-center gap-1.5 transition-colors cursor-pointer shadow-xs">
                <i data-lucide="save" class="w-3.5 h-3.5"></i>
                <span>Lưu thông số</span>
              </button>
              <button onclick="window.handleManualSync()" 
                class="px-3.5 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl font-bold text-xs flex items-center gap-1.5 transition-colors cursor-pointer shadow-xs">
                <i data-lucide="refresh-cw" class="w-3.5 h-3.5"></i>
                <span>Đồng bộ ngay</span>
              </button>
            </div>
          </div>

          <!-- Khối hướng dẫn Khởi tạo SQL 1-Click -->
          <div class="bg-amber-50/60 border border-amber-200 rounded-xl p-4 space-y-2.5">
            <div class="flex items-center gap-2 text-amber-900 font-bold text-xs">
              <i data-lucide="sparkles" class="w-4 h-4 text-amber-600"></i>
              <span>Hướng dẫn khởi tạo CSDL trên Supabase (Chỉ làm 1 lần)</span>
            </div>
            <p class="text-[11px] text-amber-800 leading-relaxed">
              Để Supabase cho phép lưu trữ thuốc mới, ca hội chẩn và báo cáo ADR, bạn chỉ cần thực hiện 2 bước đơn giản:
            </p>
            <ol class="list-decimal list-inside space-y-1.5 text-[11px] text-amber-900 font-medium pl-1">
              <li>Mở <a href="https://supabase.com/dashboard" target="_blank" class="underline font-bold text-teal-800 hover:text-teal-950">Supabase Dashboard</a> -> Chọn dự án -> Nhấp mục <strong>SQL Editor</strong> ở thanh bên trái.</li>
              <li>Bấm nút bên dưới để copy mã SQL, dán vào ô SQL Editor và nhấn <strong>RUN</strong>:</li>
            </ol>
            <div class="pt-1">
              <button onclick="window.copySupabaseSchemaSql()" 
                class="w-full py-2.5 px-4 bg-gradient-to-r from-amber-600 to-amber-700 hover:from-amber-700 hover:to-amber-800 text-white rounded-xl font-bold text-xs flex items-center justify-center gap-2 shadow-xs transition-all cursor-pointer">
                <i data-lucide="copy" class="w-4 h-4"></i>
                <span>📋 SAO CHÉP MÃ SQL KHỞI TẠO CSDL (1-CLICK)</span>
              </button>
            </div>
          </div>

        </div>

        <!-- Footer -->
        <div class="px-5 py-3 bg-slate-50 border-t border-slate-200 flex items-center justify-between text-xs">
          <span class="text-slate-400 text-[11px]">Bảo mật phân quyền Row Level Security (RLS)</span>
          <button onclick="window.closeSupabaseAuthModal()" class="px-4 py-1.5 bg-slate-200 hover:bg-slate-300 text-slate-800 rounded-xl font-bold transition-colors cursor-pointer">
            Đóng
          </button>
        </div>

      </div>
    </div>
  `;

  if (window.lucide) window.lucide.createIcons();
}

// Window global helper bindings
if (typeof window !== "undefined") {
  window.openSupabaseAuthModal = openSupabaseModal;
  window.openSupabaseModal = openSupabaseModal;
  window.closeSupabaseAuthModal = function() {
    const m = document.getElementById("supabaseAuthModal");
    if (m) m.innerHTML = "";
  };
  window.copySupabaseSchemaSql = copySupabaseSchemaSql;

  window.saveSupabaseConfig = function() {
    const urlInput = document.getElementById("cfgSupabaseUrl");
    const keyInput = document.getElementById("cfgSupabaseKey");
    if (!urlInput || !keyInput) return;
    saveSupabaseCredentials(urlInput.value.trim(), keyInput.value.trim());
    supabaseClient = null;
    alert("Đã lưu thông số kết nối Supabase thành công!");
    window.handleTestSupabaseConnection();
  };

  window.handleTestSupabaseConnection = async function() {
    const btn = document.getElementById("btnTestConnection");
    const banner = document.getElementById("supabaseStatusBanner");
    const text = document.getElementById("supabaseStatusText");
    const urlInput = document.getElementById("cfgSupabaseUrl");
    const keyInput = document.getElementById("cfgSupabaseKey");

    if (btn) btn.disabled = true;
    if (text) text.textContent = "Đang kiểm tra kết nối tới Supabase Cloud...";

    const res = await testSupabaseConnection(urlInput?.value?.trim(), keyInput?.value?.trim());

    if (btn) btn.disabled = false;
    if (res.ok) {
      if (banner) banner.className = "p-3.5 rounded-xl border border-emerald-200 bg-emerald-50 text-emerald-950 flex items-start gap-3";
      if (text) text.textContent = "✅ " + res.message;
    } else {
      if (banner) banner.className = "p-3.5 rounded-xl border border-amber-200 bg-amber-50 text-amber-950 flex items-start gap-3";
      if (text) text.textContent = "⚠️ " + res.message;
    }
  };

  window.handleManualSync = async function() {
    const text = document.getElementById("supabaseStatusText");
    if (text) text.textContent = "Đang đồng bộ dữ liệu với Supabase Cloud...";
    const ok = await syncCustomDrugsFromCloud();
    if (ok) {
      alert("Đồng bộ dữ liệu thành công từ Supabase Cloud!");
      if (text) text.textContent = "✅ Đã đồng bộ thuốc từ Cloud về thiết bị thành công!";
    } else {
      alert("Không tìm thấy dữ liệu mới trên Cloud hoặc bảng chưa được tạo. Kiểm tra lại kết nối.");
    }
  };

  window.saveDrugToCloud = saveDrugToCloud;
  window.deleteDrugFromCloud = deleteDrugFromCloud;
  window.syncCustomDrugsFromCloud = syncCustomDrugsFromCloud;
  window.uploadPdfToSupabaseStorage = uploadPdfToSupabaseStorage;
  window.autoHealMissingCloudPdfs = autoHealMissingCloudPdfs;
  window.dataUrlToBlob = dataUrlToBlob;
}

